/*
Collection Service

The Collection Service provides a comprehensive API for managing product collections and categories. It supports the creation, retrieval, updating, and deletion of product collections, as well as managing associations between collections and products. Key functionalities include: - **Collection Management**: Create, update, and delete collections of products, enabling businesses to organize products into meaningful groups for easier browsing and marketing. - **Retrieval Operations**: Retrieve collections using various identifiers such as ID, URL key, or code, and list all existing collections with optional search and filter capabilities. - **Association Management**: Establish and manage associations between collections and products, allowing products to belong to one or multiple collections. - **Bulk Operations**: Perform bulk updates on product collection associations, optimizing the management of large-scale collections. - **Count and Search**: Get counts of products in a collection and search collections using filters or product identifiers for efficient management. - **Non-Hierarchical Structure**: While the service supports flat collections and categories, it does not yet include hierarchical relationships between categories. Designed for flexibility and scalability, the Collection Service empowers businesses to organize and present their product offerings effectively while maintaining a streamlined management process.

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package productlist

import (
	"encoding/json"
)

// checks if the ProductlistSearchProductListsByIdsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductlistSearchProductListsByIdsResponse{}

// ProductlistSearchProductListsByIdsResponse Defines the structure for SearchProductListsByIdsResponse.
type ProductlistSearchProductListsByIdsResponse struct {
	// Field results of type repeated ProductListEntity.
	Results              []ProductlistProductListEntity `json:"results,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProductlistSearchProductListsByIdsResponse ProductlistSearchProductListsByIdsResponse

// NewProductlistSearchProductListsByIdsResponse instantiates a new ProductlistSearchProductListsByIdsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductlistSearchProductListsByIdsResponse() *ProductlistSearchProductListsByIdsResponse {
	this := ProductlistSearchProductListsByIdsResponse{}
	return &this
}

// NewProductlistSearchProductListsByIdsResponseWithDefaults instantiates a new ProductlistSearchProductListsByIdsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductlistSearchProductListsByIdsResponseWithDefaults() *ProductlistSearchProductListsByIdsResponse {
	this := ProductlistSearchProductListsByIdsResponse{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *ProductlistSearchProductListsByIdsResponse) GetResults() []ProductlistProductListEntity {
	if o == nil || IsNil(o.Results) {
		var ret []ProductlistProductListEntity
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistSearchProductListsByIdsResponse) GetResultsOk() ([]ProductlistProductListEntity, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *ProductlistSearchProductListsByIdsResponse) IsSetResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []ProductlistProductListEntity and assigns it to the Results field.
func (o *ProductlistSearchProductListsByIdsResponse) SetResults(v []ProductlistProductListEntity) {
	o.Results = v
}

func (o ProductlistSearchProductListsByIdsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductlistSearchProductListsByIdsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductlistSearchProductListsByIdsResponse) UnmarshalJSON(data []byte) (err error) {
	varProductlistSearchProductListsByIdsResponse := _ProductlistSearchProductListsByIdsResponse{}

	err = json.Unmarshal(data, &varProductlistSearchProductListsByIdsResponse)

	if err != nil {
		return err
	}

	*o = ProductlistSearchProductListsByIdsResponse(varProductlistSearchProductListsByIdsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *ProductlistSearchProductListsByIdsResponse) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *ProductlistSearchProductListsByIdsResponse) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableProductlistSearchProductListsByIdsResponse struct {
	value *ProductlistSearchProductListsByIdsResponse
	isSet bool
}

func (v NullableProductlistSearchProductListsByIdsResponse) Get() *ProductlistSearchProductListsByIdsResponse {
	return v.value
}

func (v *NullableProductlistSearchProductListsByIdsResponse) Set(val *ProductlistSearchProductListsByIdsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProductlistSearchProductListsByIdsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProductlistSearchProductListsByIdsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductlistSearchProductListsByIdsResponse(val *ProductlistSearchProductListsByIdsResponse) *NullableProductlistSearchProductListsByIdsResponse {
	return &NullableProductlistSearchProductListsByIdsResponse{value: val, isSet: true}
}

func (v NullableProductlistSearchProductListsByIdsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductlistSearchProductListsByIdsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
