/*
Collection Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package productlist

import (
	"encoding/json"
)

// checks if the ProductlistDeleteProductListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductlistDeleteProductListRequest{}

// ProductlistDeleteProductListRequest struct for ProductlistDeleteProductListRequest
type ProductlistDeleteProductListRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	Id *string `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProductlistDeleteProductListRequest ProductlistDeleteProductListRequest

// NewProductlistDeleteProductListRequest instantiates a new ProductlistDeleteProductListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductlistDeleteProductListRequest() *ProductlistDeleteProductListRequest {
	this := ProductlistDeleteProductListRequest{}
	return &this
}

// NewProductlistDeleteProductListRequestWithDefaults instantiates a new ProductlistDeleteProductListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductlistDeleteProductListRequestWithDefaults() *ProductlistDeleteProductListRequest {
	this := ProductlistDeleteProductListRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *ProductlistDeleteProductListRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistDeleteProductListRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *ProductlistDeleteProductListRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *ProductlistDeleteProductListRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProductlistDeleteProductListRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistDeleteProductListRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProductlistDeleteProductListRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProductlistDeleteProductListRequest) SetId(v string) {
	o.Id = &v
}

func (o ProductlistDeleteProductListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductlistDeleteProductListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductlistDeleteProductListRequest) UnmarshalJSON(data []byte) (err error) {
	varProductlistDeleteProductListRequest := _ProductlistDeleteProductListRequest{}

	err = json.Unmarshal(data, &varProductlistDeleteProductListRequest)

	if err != nil {
		return err
	}

	*o = ProductlistDeleteProductListRequest(varProductlistDeleteProductListRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *ProductlistDeleteProductListRequest) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *ProductlistDeleteProductListRequest) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableProductlistDeleteProductListRequest struct {
	value *ProductlistDeleteProductListRequest
	isSet bool
}

func (v NullableProductlistDeleteProductListRequest) Get() *ProductlistDeleteProductListRequest {
	return v.value
}

func (v *NullableProductlistDeleteProductListRequest) Set(val *ProductlistDeleteProductListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductlistDeleteProductListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductlistDeleteProductListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductlistDeleteProductListRequest(val *ProductlistDeleteProductListRequest) *NullableProductlistDeleteProductListRequest {
	return &NullableProductlistDeleteProductListRequest{value: val, isSet: true}
}

func (v NullableProductlistDeleteProductListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductlistDeleteProductListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


