/*
Collection Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product-list

import (
	"encoding/json"
)

// checks if the SetProductListAssociationsRequestAssociation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetProductListAssociationsRequestAssociation{}

// SetProductListAssociationsRequestAssociation struct for SetProductListAssociationsRequestAssociation
type SetProductListAssociationsRequestAssociation struct {
	ListId *string `json:"listId,omitempty"`
	Position *int32 `json:"position,omitempty"`
	ProductGrn *string `json:"productGrn,omitempty"`
}

// NewSetProductListAssociationsRequestAssociation instantiates a new SetProductListAssociationsRequestAssociation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetProductListAssociationsRequestAssociation() *SetProductListAssociationsRequestAssociation {
	this := SetProductListAssociationsRequestAssociation{}
	return &this
}

// NewSetProductListAssociationsRequestAssociationWithDefaults instantiates a new SetProductListAssociationsRequestAssociation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetProductListAssociationsRequestAssociationWithDefaults() *SetProductListAssociationsRequestAssociation {
	this := SetProductListAssociationsRequestAssociation{}
	return &this
}

// GetListId returns the ListId field value if set, zero value otherwise.
func (o *SetProductListAssociationsRequestAssociation) GetListId() string {
	if o == nil || IsNil(o.ListId) {
		var ret string
		return ret
	}
	return *o.ListId
}

// GetListIdOk returns a tuple with the ListId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetProductListAssociationsRequestAssociation) GetListIdOk() (*string, bool) {
	if o == nil || IsNil(o.ListId) {
		return nil, false
	}
	return o.ListId, true
}

// HasListId returns a boolean if a field has been set.
func (o *SetProductListAssociationsRequestAssociation) HasListId() bool {
	if o != nil && !IsNil(o.ListId) {
		return true
	}

	return false
}

// SetListId gets a reference to the given string and assigns it to the ListId field.
func (o *SetProductListAssociationsRequestAssociation) SetListId(v string) {
	o.ListId = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *SetProductListAssociationsRequestAssociation) GetPosition() int32 {
	if o == nil || IsNil(o.Position) {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetProductListAssociationsRequestAssociation) GetPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *SetProductListAssociationsRequestAssociation) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *SetProductListAssociationsRequestAssociation) SetPosition(v int32) {
	o.Position = &v
}

// GetProductGrn returns the ProductGrn field value if set, zero value otherwise.
func (o *SetProductListAssociationsRequestAssociation) GetProductGrn() string {
	if o == nil || IsNil(o.ProductGrn) {
		var ret string
		return ret
	}
	return *o.ProductGrn
}

// GetProductGrnOk returns a tuple with the ProductGrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetProductListAssociationsRequestAssociation) GetProductGrnOk() (*string, bool) {
	if o == nil || IsNil(o.ProductGrn) {
		return nil, false
	}
	return o.ProductGrn, true
}

// HasProductGrn returns a boolean if a field has been set.
func (o *SetProductListAssociationsRequestAssociation) HasProductGrn() bool {
	if o != nil && !IsNil(o.ProductGrn) {
		return true
	}

	return false
}

// SetProductGrn gets a reference to the given string and assigns it to the ProductGrn field.
func (o *SetProductListAssociationsRequestAssociation) SetProductGrn(v string) {
	o.ProductGrn = &v
}

func (o SetProductListAssociationsRequestAssociation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetProductListAssociationsRequestAssociation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ListId) {
		toSerialize["listId"] = o.ListId
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.ProductGrn) {
		toSerialize["productGrn"] = o.ProductGrn
	}
	return toSerialize, nil
}

type NullableSetProductListAssociationsRequestAssociation struct {
	value *SetProductListAssociationsRequestAssociation
	isSet bool
}

func (v NullableSetProductListAssociationsRequestAssociation) Get() *SetProductListAssociationsRequestAssociation {
	return v.value
}

func (v *NullableSetProductListAssociationsRequestAssociation) Set(val *SetProductListAssociationsRequestAssociation) {
	v.value = val
	v.isSet = true
}

func (v NullableSetProductListAssociationsRequestAssociation) IsSet() bool {
	return v.isSet
}

func (v *NullableSetProductListAssociationsRequestAssociation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetProductListAssociationsRequestAssociation(val *SetProductListAssociationsRequestAssociation) *NullableSetProductListAssociationsRequestAssociation {
	return &NullableSetProductListAssociationsRequestAssociation{value: val, isSet: true}
}

func (v NullableSetProductListAssociationsRequestAssociation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetProductListAssociationsRequestAssociation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


