/*
Collection Service

The Collection Service provides a comprehensive API for managing product collections and categories. It supports the creation, retrieval, updating, and deletion of product collections, as well as managing associations between collections and products. Key functionalities include: - **Collection Management**: Create, update, and delete collections of products, enabling businesses to organize products into meaningful groups for easier browsing and marketing. - **Retrieval Operations**: Retrieve collections using various identifiers such as ID, URL key, or code, and list all existing collections with optional search and filter capabilities. - **Association Management**: Establish and manage associations between collections and products, allowing products to belong to one or multiple collections. - **Bulk Operations**: Perform bulk updates on product collection associations, optimizing the management of large-scale collections. - **Count and Search**: Get counts of products in a collection and search collections using filters or product identifiers for efficient management. - **Non-Hierarchical Structure**: While the service supports flat collections and categories, it does not yet include hierarchical relationships between categories. Designed for flexibility and scalability, the Collection Service empowers businesses to organize and present their product offerings effectively while maintaining a streamlined management process.

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package productlist

import (
	"encoding/json"
)

// checks if the ProductlistProductListAssociation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductlistProductListAssociation{}

// ProductlistProductListAssociation Represents an association between a product and a collection, including metadata like position.
type ProductlistProductListAssociation struct {
	// The unique identifier for the product-collection association.
	Id *string `json:"id,omitempty"`
	// Field list_id of type string.
	ListId  *string `json:"listId,omitempty"`
	ListGrn *string `json:"listGrn,omitempty"`
	// Defines the position of the product within the collection.
	Position *int32 `json:"position,omitempty"`
	// Field product_grn of type string.
	ProductGrn           *string `json:"productGrn,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProductlistProductListAssociation ProductlistProductListAssociation

// NewProductlistProductListAssociation instantiates a new ProductlistProductListAssociation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductlistProductListAssociation() *ProductlistProductListAssociation {
	this := ProductlistProductListAssociation{}
	return &this
}

// NewProductlistProductListAssociationWithDefaults instantiates a new ProductlistProductListAssociation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductlistProductListAssociationWithDefaults() *ProductlistProductListAssociation {
	this := ProductlistProductListAssociation{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProductlistProductListAssociation) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistProductListAssociation) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProductlistProductListAssociation) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProductlistProductListAssociation) SetId(v string) {
	o.Id = &v
}

// GetListId returns the ListId field value if set, zero value otherwise.
func (o *ProductlistProductListAssociation) GetListId() string {
	if o == nil || IsNil(o.ListId) {
		var ret string
		return ret
	}
	return *o.ListId
}

// GetListIdOk returns a tuple with the ListId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistProductListAssociation) GetListIdOk() (*string, bool) {
	if o == nil || IsNil(o.ListId) {
		return nil, false
	}
	return o.ListId, true
}

// HasListId returns a boolean if a field has been set.
func (o *ProductlistProductListAssociation) HasListId() bool {
	if o != nil && !IsNil(o.ListId) {
		return true
	}

	return false
}

// SetListId gets a reference to the given string and assigns it to the ListId field.
func (o *ProductlistProductListAssociation) SetListId(v string) {
	o.ListId = &v
}

// GetListGrn returns the ListGrn field value if set, zero value otherwise.
func (o *ProductlistProductListAssociation) GetListGrn() string {
	if o == nil || IsNil(o.ListGrn) {
		var ret string
		return ret
	}
	return *o.ListGrn
}

// GetListGrnOk returns a tuple with the ListGrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistProductListAssociation) GetListGrnOk() (*string, bool) {
	if o == nil || IsNil(o.ListGrn) {
		return nil, false
	}
	return o.ListGrn, true
}

// HasListGrn returns a boolean if a field has been set.
func (o *ProductlistProductListAssociation) HasListGrn() bool {
	if o != nil && !IsNil(o.ListGrn) {
		return true
	}

	return false
}

// SetListGrn gets a reference to the given string and assigns it to the ListGrn field.
func (o *ProductlistProductListAssociation) SetListGrn(v string) {
	o.ListGrn = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *ProductlistProductListAssociation) GetPosition() int32 {
	if o == nil || IsNil(o.Position) {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistProductListAssociation) GetPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *ProductlistProductListAssociation) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *ProductlistProductListAssociation) SetPosition(v int32) {
	o.Position = &v
}

// GetProductGrn returns the ProductGrn field value if set, zero value otherwise.
func (o *ProductlistProductListAssociation) GetProductGrn() string {
	if o == nil || IsNil(o.ProductGrn) {
		var ret string
		return ret
	}
	return *o.ProductGrn
}

// GetProductGrnOk returns a tuple with the ProductGrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistProductListAssociation) GetProductGrnOk() (*string, bool) {
	if o == nil || IsNil(o.ProductGrn) {
		return nil, false
	}
	return o.ProductGrn, true
}

// HasProductGrn returns a boolean if a field has been set.
func (o *ProductlistProductListAssociation) HasProductGrn() bool {
	if o != nil && !IsNil(o.ProductGrn) {
		return true
	}

	return false
}

// SetProductGrn gets a reference to the given string and assigns it to the ProductGrn field.
func (o *ProductlistProductListAssociation) SetProductGrn(v string) {
	o.ProductGrn = &v
}

func (o ProductlistProductListAssociation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductlistProductListAssociation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ListId) {
		toSerialize["listId"] = o.ListId
	}
	if !IsNil(o.ListGrn) {
		toSerialize["listGrn"] = o.ListGrn
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.ProductGrn) {
		toSerialize["productGrn"] = o.ProductGrn
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductlistProductListAssociation) UnmarshalJSON(data []byte) (err error) {
	varProductlistProductListAssociation := _ProductlistProductListAssociation{}

	err = json.Unmarshal(data, &varProductlistProductListAssociation)

	if err != nil {
		return err
	}

	*o = ProductlistProductListAssociation(varProductlistProductListAssociation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "listId")
		delete(additionalProperties, "listGrn")
		delete(additionalProperties, "position")
		delete(additionalProperties, "productGrn")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *ProductlistProductListAssociation) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *ProductlistProductListAssociation) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableProductlistProductListAssociation struct {
	value *ProductlistProductListAssociation
	isSet bool
}

func (v NullableProductlistProductListAssociation) Get() *ProductlistProductListAssociation {
	return v.value
}

func (v *NullableProductlistProductListAssociation) Set(val *ProductlistProductListAssociation) {
	v.value = val
	v.isSet = true
}

func (v NullableProductlistProductListAssociation) IsSet() bool {
	return v.isSet
}

func (v *NullableProductlistProductListAssociation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductlistProductListAssociation(val *ProductlistProductListAssociation) *NullableProductlistProductListAssociation {
	return &NullableProductlistProductListAssociation{value: val, isSet: true}
}

func (v NullableProductlistProductListAssociation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductlistProductListAssociation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
