/*
Collection Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package productlist

import (
	"encoding/json"
)

// checks if the ProductlistGetProductListsCountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductlistGetProductListsCountRequest{}

// ProductlistGetProductListsCountRequest struct for ProductlistGetProductListsCountRequest
type ProductlistGetProductListsCountRequest struct {
	TenantId             *string `json:"tenantId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProductlistGetProductListsCountRequest ProductlistGetProductListsCountRequest

// NewProductlistGetProductListsCountRequest instantiates a new ProductlistGetProductListsCountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductlistGetProductListsCountRequest() *ProductlistGetProductListsCountRequest {
	this := ProductlistGetProductListsCountRequest{}
	return &this
}

// NewProductlistGetProductListsCountRequestWithDefaults instantiates a new ProductlistGetProductListsCountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductlistGetProductListsCountRequestWithDefaults() *ProductlistGetProductListsCountRequest {
	this := ProductlistGetProductListsCountRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *ProductlistGetProductListsCountRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistGetProductListsCountRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *ProductlistGetProductListsCountRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *ProductlistGetProductListsCountRequest) SetTenantId(v string) {
	o.TenantId = &v
}

func (o ProductlistGetProductListsCountRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductlistGetProductListsCountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductlistGetProductListsCountRequest) UnmarshalJSON(data []byte) (err error) {
	varProductlistGetProductListsCountRequest := _ProductlistGetProductListsCountRequest{}

	err = json.Unmarshal(data, &varProductlistGetProductListsCountRequest)

	if err != nil {
		return err
	}

	*o = ProductlistGetProductListsCountRequest(varProductlistGetProductListsCountRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *ProductlistGetProductListsCountRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *ProductlistGetProductListsCountRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableProductlistGetProductListsCountRequest struct {
	value *ProductlistGetProductListsCountRequest
	isSet bool
}

func (v NullableProductlistGetProductListsCountRequest) Get() *ProductlistGetProductListsCountRequest {
	return v.value
}

func (v *NullableProductlistGetProductListsCountRequest) Set(val *ProductlistGetProductListsCountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductlistGetProductListsCountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductlistGetProductListsCountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductlistGetProductListsCountRequest(val *ProductlistGetProductListsCountRequest) *NullableProductlistGetProductListsCountRequest {
	return &NullableProductlistGetProductListsCountRequest{value: val, isSet: true}
}

func (v NullableProductlistGetProductListsCountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductlistGetProductListsCountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
