/*
Collection Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package productlist

import (
	"encoding/json"
)

// checks if the ProductlistGetProductListByCodeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductlistGetProductListByCodeRequest{}

// ProductlistGetProductListByCodeRequest struct for ProductlistGetProductListByCodeRequest
type ProductlistGetProductListByCodeRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	Code *string `json:"code,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProductlistGetProductListByCodeRequest ProductlistGetProductListByCodeRequest

// NewProductlistGetProductListByCodeRequest instantiates a new ProductlistGetProductListByCodeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductlistGetProductListByCodeRequest() *ProductlistGetProductListByCodeRequest {
	this := ProductlistGetProductListByCodeRequest{}
	return &this
}

// NewProductlistGetProductListByCodeRequestWithDefaults instantiates a new ProductlistGetProductListByCodeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductlistGetProductListByCodeRequestWithDefaults() *ProductlistGetProductListByCodeRequest {
	this := ProductlistGetProductListByCodeRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *ProductlistGetProductListByCodeRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistGetProductListByCodeRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// &#39;Has&#39;TenantId returns a boolean if a field has been set.
func (o *ProductlistGetProductListByCodeRequest) &#39;Has&#39;TenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *ProductlistGetProductListByCodeRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ProductlistGetProductListByCodeRequest) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistGetProductListByCodeRequest) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// &#39;Has&#39;Code returns a boolean if a field has been set.
func (o *ProductlistGetProductListByCodeRequest) &#39;Has&#39;Code() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ProductlistGetProductListByCodeRequest) SetCode(v string) {
	o.Code = &v
}

func (o ProductlistGetProductListByCodeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductlistGetProductListByCodeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductlistGetProductListByCodeRequest) UnmarshalJSON(data []byte) (err error) {
	varProductlistGetProductListByCodeRequest := _ProductlistGetProductListByCodeRequest{}

	err = json.Unmarshal(data, &varProductlistGetProductListByCodeRequest)

	if err != nil {
		return err
	}

	*o = ProductlistGetProductListByCodeRequest(varProductlistGetProductListByCodeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "code")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *ProductlistGetProductListByCodeRequest) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *ProductlistGetProductListByCodeRequest) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableProductlistGetProductListByCodeRequest struct {
	value *ProductlistGetProductListByCodeRequest
	isSet bool
}

func (v NullableProductlistGetProductListByCodeRequest) Get() *ProductlistGetProductListByCodeRequest {
	return v.value
}

func (v *NullableProductlistGetProductListByCodeRequest) Set(val *ProductlistGetProductListByCodeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductlistGetProductListByCodeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductlistGetProductListByCodeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductlistGetProductListByCodeRequest(val *ProductlistGetProductListByCodeRequest) *NullableProductlistGetProductListByCodeRequest {
	return &NullableProductlistGetProductListByCodeRequest{value: val, isSet: true}
}

func (v NullableProductlistGetProductListByCodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductlistGetProductListByCodeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


