/*
Collection Service

API for managing collection

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product-list

import (
	"encoding/json"
)

// checks if the ProductlistBulkUpdateProductListAssociationsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductlistBulkUpdateProductListAssociationsRequest{}

// ProductlistBulkUpdateProductListAssociationsRequest struct for ProductlistBulkUpdateProductListAssociationsRequest
type ProductlistBulkUpdateProductListAssociationsRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	ProductListAssociations []ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation `json:"productListAssociations,omitempty"`
}

// NewProductlistBulkUpdateProductListAssociationsRequest instantiates a new ProductlistBulkUpdateProductListAssociationsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductlistBulkUpdateProductListAssociationsRequest() *ProductlistBulkUpdateProductListAssociationsRequest {
	this := ProductlistBulkUpdateProductListAssociationsRequest{}
	return &this
}

// NewProductlistBulkUpdateProductListAssociationsRequestWithDefaults instantiates a new ProductlistBulkUpdateProductListAssociationsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductlistBulkUpdateProductListAssociationsRequestWithDefaults() *ProductlistBulkUpdateProductListAssociationsRequest {
	this := ProductlistBulkUpdateProductListAssociationsRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *ProductlistBulkUpdateProductListAssociationsRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistBulkUpdateProductListAssociationsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *ProductlistBulkUpdateProductListAssociationsRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *ProductlistBulkUpdateProductListAssociationsRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetProductListAssociations returns the ProductListAssociations field value if set, zero value otherwise.
func (o *ProductlistBulkUpdateProductListAssociationsRequest) GetProductListAssociations() []ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation {
	if o == nil || IsNil(o.ProductListAssociations) {
		var ret []ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation
		return ret
	}
	return o.ProductListAssociations
}

// GetProductListAssociationsOk returns a tuple with the ProductListAssociations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistBulkUpdateProductListAssociationsRequest) GetProductListAssociationsOk() ([]ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation, bool) {
	if o == nil || IsNil(o.ProductListAssociations) {
		return nil, false
	}
	return o.ProductListAssociations, true
}

// HasProductListAssociations returns a boolean if a field has been set.
func (o *ProductlistBulkUpdateProductListAssociationsRequest) HasProductListAssociations() bool {
	if o != nil && !IsNil(o.ProductListAssociations) {
		return true
	}

	return false
}

// SetProductListAssociations gets a reference to the given []ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation and assigns it to the ProductListAssociations field.
func (o *ProductlistBulkUpdateProductListAssociationsRequest) SetProductListAssociations(v []ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation) {
	o.ProductListAssociations = v
}

func (o ProductlistBulkUpdateProductListAssociationsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductlistBulkUpdateProductListAssociationsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.ProductListAssociations) {
		toSerialize["productListAssociations"] = o.ProductListAssociations
	}
	return toSerialize, nil
}

type NullableProductlistBulkUpdateProductListAssociationsRequest struct {
	value *ProductlistBulkUpdateProductListAssociationsRequest
	isSet bool
}

func (v NullableProductlistBulkUpdateProductListAssociationsRequest) Get() *ProductlistBulkUpdateProductListAssociationsRequest {
	return v.value
}

func (v *NullableProductlistBulkUpdateProductListAssociationsRequest) Set(val *ProductlistBulkUpdateProductListAssociationsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductlistBulkUpdateProductListAssociationsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductlistBulkUpdateProductListAssociationsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductlistBulkUpdateProductListAssociationsRequest(val *ProductlistBulkUpdateProductListAssociationsRequest) *NullableProductlistBulkUpdateProductListAssociationsRequest {
	return &NullableProductlistBulkUpdateProductListAssociationsRequest{value: val, isSet: true}
}

func (v NullableProductlistBulkUpdateProductListAssociationsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductlistBulkUpdateProductListAssociationsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


