/*
Collection Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package productlist

import (
	"encoding/json"
)

// checks if the ProductlistGetProductListByUrlKeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductlistGetProductListByUrlKeyResponse{}

// ProductlistGetProductListByUrlKeyResponse struct for ProductlistGetProductListByUrlKeyResponse
type ProductlistGetProductListByUrlKeyResponse struct {
	List *ProductlistProductListEntity `json:"list,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProductlistGetProductListByUrlKeyResponse ProductlistGetProductListByUrlKeyResponse

// NewProductlistGetProductListByUrlKeyResponse instantiates a new ProductlistGetProductListByUrlKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductlistGetProductListByUrlKeyResponse() *ProductlistGetProductListByUrlKeyResponse {
	this := ProductlistGetProductListByUrlKeyResponse{}
	return &this
}

// NewProductlistGetProductListByUrlKeyResponseWithDefaults instantiates a new ProductlistGetProductListByUrlKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductlistGetProductListByUrlKeyResponseWithDefaults() *ProductlistGetProductListByUrlKeyResponse {
	this := ProductlistGetProductListByUrlKeyResponse{}
	return &this
}

// GetList returns the List field value if set, zero value otherwise.
func (o *ProductlistGetProductListByUrlKeyResponse) GetList() ProductlistProductListEntity {
	if o == nil || IsNil(o.List) {
		var ret ProductlistProductListEntity
		return ret
	}
	return *o.List
}

// GetListOk returns a tuple with the List field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistGetProductListByUrlKeyResponse) GetListOk() (*ProductlistProductListEntity, bool) {
	if o == nil || IsNil(o.List) {
		return nil, false
	}
	return o.List, true
}

// &#39;Has&#39;List returns a boolean if a field has been set.
func (o *ProductlistGetProductListByUrlKeyResponse) &#39;Has&#39;List() bool {
	if o != nil && !IsNil(o.List) {
		return true
	}

	return false
}

// SetList gets a reference to the given ProductlistProductListEntity and assigns it to the List field.
func (o *ProductlistGetProductListByUrlKeyResponse) SetList(v ProductlistProductListEntity) {
	o.List = &v
}

func (o ProductlistGetProductListByUrlKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductlistGetProductListByUrlKeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.List) {
		toSerialize["list"] = o.List
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductlistGetProductListByUrlKeyResponse) UnmarshalJSON(data []byte) (err error) {
	varProductlistGetProductListByUrlKeyResponse := _ProductlistGetProductListByUrlKeyResponse{}

	err = json.Unmarshal(data, &varProductlistGetProductListByUrlKeyResponse)

	if err != nil {
		return err
	}

	*o = ProductlistGetProductListByUrlKeyResponse(varProductlistGetProductListByUrlKeyResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "list")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *ProductlistGetProductListByUrlKeyResponse) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *ProductlistGetProductListByUrlKeyResponse) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableProductlistGetProductListByUrlKeyResponse struct {
	value *ProductlistGetProductListByUrlKeyResponse
	isSet bool
}

func (v NullableProductlistGetProductListByUrlKeyResponse) Get() *ProductlistGetProductListByUrlKeyResponse {
	return v.value
}

func (v *NullableProductlistGetProductListByUrlKeyResponse) Set(val *ProductlistGetProductListByUrlKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProductlistGetProductListByUrlKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProductlistGetProductListByUrlKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductlistGetProductListByUrlKeyResponse(val *ProductlistGetProductListByUrlKeyResponse) *NullableProductlistGetProductListByUrlKeyResponse {
	return &NullableProductlistGetProductListByUrlKeyResponse{value: val, isSet: true}
}

func (v NullableProductlistGetProductListByUrlKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductlistGetProductListByUrlKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


