/*
product-list/bulk_update_product_list_associations.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product-list

import (
	"encoding/json"
)

// checks if the ProductlistGetProductListByIdRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductlistGetProductListByIdRequest{}

// ProductlistGetProductListByIdRequest struct for ProductlistGetProductListByIdRequest
type ProductlistGetProductListByIdRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	Id *string `json:"id,omitempty"`
}

// NewProductlistGetProductListByIdRequest instantiates a new ProductlistGetProductListByIdRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductlistGetProductListByIdRequest() *ProductlistGetProductListByIdRequest {
	this := ProductlistGetProductListByIdRequest{}
	return &this
}

// NewProductlistGetProductListByIdRequestWithDefaults instantiates a new ProductlistGetProductListByIdRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductlistGetProductListByIdRequestWithDefaults() *ProductlistGetProductListByIdRequest {
	this := ProductlistGetProductListByIdRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *ProductlistGetProductListByIdRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistGetProductListByIdRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *ProductlistGetProductListByIdRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *ProductlistGetProductListByIdRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProductlistGetProductListByIdRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistGetProductListByIdRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProductlistGetProductListByIdRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProductlistGetProductListByIdRequest) SetId(v string) {
	o.Id = &v
}

func (o ProductlistGetProductListByIdRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductlistGetProductListByIdRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableProductlistGetProductListByIdRequest struct {
	value *ProductlistGetProductListByIdRequest
	isSet bool
}

func (v NullableProductlistGetProductListByIdRequest) Get() *ProductlistGetProductListByIdRequest {
	return v.value
}

func (v *NullableProductlistGetProductListByIdRequest) Set(val *ProductlistGetProductListByIdRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductlistGetProductListByIdRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductlistGetProductListByIdRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductlistGetProductListByIdRequest(val *ProductlistGetProductListByIdRequest) *NullableProductlistGetProductListByIdRequest {
	return &NullableProductlistGetProductListByIdRequest{value: val, isSet: true}
}

func (v NullableProductlistGetProductListByIdRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductlistGetProductListByIdRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


