/*
Collection Service

API for managing collection

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product-list

import (
	"encoding/json"
)

// checks if the ProductlistListProductListAssociationsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductlistListProductListAssociationsResponse{}

// ProductlistListProductListAssociationsResponse struct for ProductlistListProductListAssociationsResponse
type ProductlistListProductListAssociationsResponse struct {
	Associations []ProductlistProductListAssociation `json:"associations,omitempty"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// NewProductlistListProductListAssociationsResponse instantiates a new ProductlistListProductListAssociationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductlistListProductListAssociationsResponse() *ProductlistListProductListAssociationsResponse {
	this := ProductlistListProductListAssociationsResponse{}
	return &this
}

// NewProductlistListProductListAssociationsResponseWithDefaults instantiates a new ProductlistListProductListAssociationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductlistListProductListAssociationsResponseWithDefaults() *ProductlistListProductListAssociationsResponse {
	this := ProductlistListProductListAssociationsResponse{}
	return &this
}

// GetAssociations returns the Associations field value if set, zero value otherwise.
func (o *ProductlistListProductListAssociationsResponse) GetAssociations() []ProductlistProductListAssociation {
	if o == nil || IsNil(o.Associations) {
		var ret []ProductlistProductListAssociation
		return ret
	}
	return o.Associations
}

// GetAssociationsOk returns a tuple with the Associations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistListProductListAssociationsResponse) GetAssociationsOk() ([]ProductlistProductListAssociation, bool) {
	if o == nil || IsNil(o.Associations) {
		return nil, false
	}
	return o.Associations, true
}

// HasAssociations returns a boolean if a field has been set.
func (o *ProductlistListProductListAssociationsResponse) HasAssociations() bool {
	if o != nil && !IsNil(o.Associations) {
		return true
	}

	return false
}

// SetAssociations gets a reference to the given []ProductlistProductListAssociation and assigns it to the Associations field.
func (o *ProductlistListProductListAssociationsResponse) SetAssociations(v []ProductlistProductListAssociation) {
	o.Associations = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *ProductlistListProductListAssociationsResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductlistListProductListAssociationsResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *ProductlistListProductListAssociationsResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *ProductlistListProductListAssociationsResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

func (o ProductlistListProductListAssociationsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductlistListProductListAssociationsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Associations) {
		toSerialize["associations"] = o.Associations
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	return toSerialize, nil
}

type NullableProductlistListProductListAssociationsResponse struct {
	value *ProductlistListProductListAssociationsResponse
	isSet bool
}

func (v NullableProductlistListProductListAssociationsResponse) Get() *ProductlistListProductListAssociationsResponse {
	return v.value
}

func (v *NullableProductlistListProductListAssociationsResponse) Set(val *ProductlistListProductListAssociationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProductlistListProductListAssociationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProductlistListProductListAssociationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductlistListProductListAssociationsResponse(val *ProductlistListProductListAssociationsResponse) *NullableProductlistListProductListAssociationsResponse {
	return &NullableProductlistListProductListAssociationsResponse{value: val, isSet: true}
}

func (v NullableProductlistListProductListAssociationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductlistListProductListAssociationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


