/*
Collection Service

The Collection Service provides a comprehensive API for managing product collections and categories. It supports the creation, retrieval, updating, and deletion of product collections, as well as managing associations between collections and products. Key functionalities include: - **Collection Management**: Create, update, and delete collections of products, enabling businesses to organize products into meaningful groups for easier browsing and marketing. - **Retrieval Operations**: Retrieve collections using various identifiers such as ID, URL key, or code, and list all existing collections with optional search and filter capabilities. - **Association Management**: Establish and manage associations between collections and products, allowing products to belong to one or multiple collections. - **Bulk Operations**: Perform bulk updates on product collection associations, optimizing the management of large-scale collections. - **Count and Search**: Get counts of products in a collection and search collections using filters or product identifiers for efficient management. - **Non-Hierarchical Structure**: While the service supports flat collections and categories, it does not yet include hierarchical relationships between categories. Designed for flexibility and scalability, the Collection Service empowers businesses to organize and present their product offerings effectively while maintaining a streamlined management process.

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package productlist

import (
	"encoding/json"
)

// checks if the SearchProductListsRequestQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchProductListsRequestQuery{}

// SearchProductListsRequestQuery struct for SearchProductListsRequestQuery
type SearchProductListsRequestQuery struct {
	Attributes           []string `json:"attributes,omitempty"`
	Value                *string  `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SearchProductListsRequestQuery SearchProductListsRequestQuery

// NewSearchProductListsRequestQuery instantiates a new SearchProductListsRequestQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchProductListsRequestQuery() *SearchProductListsRequestQuery {
	this := SearchProductListsRequestQuery{}
	return &this
}

// NewSearchProductListsRequestQueryWithDefaults instantiates a new SearchProductListsRequestQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchProductListsRequestQueryWithDefaults() *SearchProductListsRequestQuery {
	this := SearchProductListsRequestQuery{}
	return &this
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *SearchProductListsRequestQuery) GetAttributes() []string {
	if o == nil || IsNil(o.Attributes) {
		var ret []string
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchProductListsRequestQuery) GetAttributesOk() ([]string, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *SearchProductListsRequestQuery) IsSetAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given []string and assigns it to the Attributes field.
func (o *SearchProductListsRequestQuery) SetAttributes(v []string) {
	o.Attributes = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *SearchProductListsRequestQuery) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchProductListsRequestQuery) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *SearchProductListsRequestQuery) IsSetValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *SearchProductListsRequestQuery) SetValue(v string) {
	o.Value = &v
}

func (o SearchProductListsRequestQuery) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchProductListsRequestQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchProductListsRequestQuery) UnmarshalJSON(data []byte) (err error) {
	varSearchProductListsRequestQuery := _SearchProductListsRequestQuery{}

	err = json.Unmarshal(data, &varSearchProductListsRequestQuery)

	if err != nil {
		return err
	}

	*o = SearchProductListsRequestQuery(varSearchProductListsRequestQuery)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "attributes")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *SearchProductListsRequestQuery) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *SearchProductListsRequestQuery) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableSearchProductListsRequestQuery struct {
	value *SearchProductListsRequestQuery
	isSet bool
}

func (v NullableSearchProductListsRequestQuery) Get() *SearchProductListsRequestQuery {
	return v.value
}

func (v *NullableSearchProductListsRequestQuery) Set(val *SearchProductListsRequestQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchProductListsRequestQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchProductListsRequestQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchProductListsRequestQuery(val *SearchProductListsRequestQuery) *NullableSearchProductListsRequestQuery {
	return &NullableSearchProductListsRequestQuery{value: val, isSet: true}
}

func (v NullableSearchProductListsRequestQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchProductListsRequestQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
